# Generated by Django 2.2.16 on 2022-07-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_org', '0003_auto_20220702_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='login_user',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='message',
            field=models.CharField(default='Ok', max_length=100, null=True),
        ),
    ]
