# Generated by Django 2.2.16 on 2022-07-02 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reg_org', '0004_auto_20220702_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='RegisterHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('register_user', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reg_org.Organization')),
            ],
        ),
    ]
