# Generated by Django 2.2.16 on 2022-07-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_org', '0006_auto_20220703_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
