# Generated by Django 2.2.16 on 2022-07-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_org', '0007_loginhistory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='status',
            field=models.CharField(default='success', max_length=100, null=True),
        ),
    ]
